name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 如果有前端构建步骤（如 Vite/webpack），请在这里添加
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build

      - name: Inject environment variables for frontend
        run: |
          echo "window.OPENROUTER_API_KEY='${{ secrets.OPENROUTER_API_KEY }}';window.SITE_URL='${{ secrets.SITE_URL || 'https://<your-pages-domain>' }}';window.SITE_NAME='Word Root Explorer';" > /home/runner/work/Word-Root-Explorer/Word-Root-Explorer/local.env.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/Word-Root-Explorer/Word-Root-Explorer
